# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_gmm <- function(X, k, max_iter = 100L, tol = 1e-6) {
    .Call(`_EMLab_em_gmm`, X, k, max_iter, tol)
}

